/**
 * Built-in UI strings.
 *
 * These are the defaults shipped with the bundle. Everything the admin saves in
 * Admin → Language Management overrides the matching key at runtime, so a label
 * can be reworded without a deploy — and a brand-new language still renders a
 * complete interface from day one.
 */
export const DEFAULT_STRINGS = {
  'nav.home': 'Home',
  'nav.projects': 'Projects',
  'nav.services': 'Services',
  'nav.about': 'About',
  'nav.blog': 'Blog',
  'nav.contact': 'Contact',
  'nav.resume': 'Résumé',

  'action.viewAll': 'View all',
  'action.readMore': 'Read more',
  'action.viewProject': 'View project',
  'action.visitSite': 'Visit website',
  'action.send': 'Send message',
  'action.sending': 'Sending…',
  'action.download': 'Download PDF',
  'action.print': 'Print version',
  'action.search': 'Search',
  'action.clear': 'Clear',
  'action.retry': 'Try again',
  'action.back': 'Back',

  'section.about': 'About',
  'section.skills': 'Skills & technologies',
  'section.services': 'Services',
  'section.projects': 'Selected projects',
  'section.experience': 'Experience',
  'section.testimonials': 'Testimonials',
  'section.blog': 'Latest articles',
  'section.contact': 'Contact',
  'section.education': 'Education',
  'section.certifications': 'Certifications',
  'section.stats': 'By the numbers',

  'label.allProjects': 'All projects',
  'label.allPosts': 'All articles',
  'label.category': 'Category',
  'label.technology': 'Technology',
  'label.sort': 'Sort',
  'label.latest': 'Newest',
  'label.oldest': 'Oldest',
  'label.featured': 'Featured',
  'label.byTitle': 'By title',
  'label.tags': 'Tags',
  'label.share': 'Share',
  'label.related': 'Related',
  'label.role': 'Role',
  'label.client': 'Client',
  'label.delivered': 'Delivered',
  'label.location': 'Location',
  'label.stack': 'Stack',
  'label.level': 'Level',
  'label.present': 'Present',
  'label.minRead': 'min read',
  'label.results': 'Results',
  'label.challenge': 'Challenge',
  'label.solution': 'Solution',

  'state.loading': 'Loading…',
  'state.empty': 'Nothing here yet.',
  'state.emptyProjects': 'No projects match these filters.',
  'state.emptyPosts': 'No articles published yet.',
  'state.error': 'Something went wrong. Please try again.',
  'state.notFound': 'This page could not be found.',
  'state.searchHint': 'Type at least two characters.',

  'form.name': 'Name',
  'form.email': 'Email',
  'form.phone': 'Phone',
  'form.company': 'Company',
  'form.subject': 'Subject',
  'form.message': 'Message',
  'form.budget': 'Budget',
  'form.service': 'Service you need',
  'form.required': 'Required',
  'form.success': 'Your message arrived — thanks for reaching out!',
  'form.error': 'Please review the highlighted fields.',

  'a11y.menu': 'Menu',
  'a11y.close': 'Close',
  'a11y.language': 'Language',
  'a11y.themeToggle': 'Switch theme',
  'a11y.skip': 'Skip to content',
  'a11y.previous': 'Previous',
  'a11y.next': 'Next',
};
